//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Prevodi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Prevodi() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Prevodi", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijava cene za prevoz.
        /// </summary>
        internal static string res_01 {
            get {
                return ResourceManager.GetString("res_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobrodošli na strani za prijavo cene!.
        /// </summary>
        internal static string res_02 {
            get {
                return ResourceManager.GetString("res_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preko elektronske pošte ste prejeli povpraševanje za oddajo cene za prevoz. Oddajte ceno in prehitite konkurenco!.
        /// </summary>
        internal static string res_03 {
            get {
                return ResourceManager.GetString("res_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za kakršnakoli dodatna vprašanja smo vam na voljo na spodaj navedenih kontaktnih podatkih..
        /// </summary>
        internal static string res_04 {
            get {
                return ResourceManager.GetString("res_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt.
        /// </summary>
        internal static string res_05 {
            get {
                return ResourceManager.GetString("res_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kje nas najdete?.
        /// </summary>
        internal static string res_06 {
            get {
                return ResourceManager.GetString("res_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrbje 80A,.
        /// </summary>
        internal static string res_07 {
            get {
                return ResourceManager.GetString("res_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3310 Žalec, Slovenija.
        /// </summary>
        internal static string res_08 {
            get {
                return ResourceManager.GetString("res_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon &amp; FAX.
        /// </summary>
        internal static string res_09 {
            get {
                return ResourceManager.GetString("res_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elektronska pošta.
        /// </summary>
        internal static string res_10 {
            get {
                return ResourceManager.GetString("res_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijava prevoznika.
        /// </summary>
        internal static string res_11 {
            get {
                return ResourceManager.GetString("res_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premagajte konkurenco.
        /// </summary>
        internal static string res_12 {
            get {
                return ResourceManager.GetString("res_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosimo vas, da na desni strani, v polje PRIJAVNA CENA vpišete ceno, za katero ste pripravljeni peljati blago na relaciji, ki je navedena na desni strani. Ostali podatki o prevozu, so prav tako zapisani na desni strani. 
        ///Opozarjamo, da z oddajo cene, jamčite za ceno in se obvežete, da boste zagotovili prevoz na zapisani relaciji in na zapisan datum (DATUM NAKLADA), v kolikor boste izbrani za prevoz..
        /// </summary>
        internal static string res_13 {
            get {
                return ResourceManager.GetString("res_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opozarjamo, da z oddajo cene, jamčite za ceno in se obvežete, da boste zagotovili prevoz na zapisani relaciji in na zapisan datum (DATUM NAKLADA), v kolikor boste izbrani za prevoz..
        /// </summary>
        internal static string res_14 {
            get {
                return ResourceManager.GetString("res_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ŠT. ODPOKLICA.
        /// </summary>
        internal static string res_15 {
            get {
                return ResourceManager.GetString("res_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RELACIJA.
        /// </summary>
        internal static string res_16 {
            get {
                return ResourceManager.GetString("res_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PODATKI O BLAGU.
        /// </summary>
        internal static string res_17 {
            get {
                return ResourceManager.GetString("res_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATUM NAKLADA.
        /// </summary>
        internal static string res_18 {
            get {
                return ResourceManager.GetString("res_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREDLAGANA CENA.
        /// </summary>
        internal static string res_19 {
            get {
                return ResourceManager.GetString("res_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRIJAVNA CENA.
        /// </summary>
        internal static string res_20 {
            get {
                return ResourceManager.GetString("res_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STRINJAM SE S POGOJI PRIJAVE.
        /// </summary>
        internal static string res_21 {
            get {
                return ResourceManager.GetString("res_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oddaj ceno.
        /// </summary>
        internal static string res_22 {
            get {
                return ResourceManager.GetString("res_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogoji prijave.
        /// </summary>
        internal static string res_23 {
            get {
                return ResourceManager.GetString("res_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opozarjamo, da z oddajo cene, jamčite za ceno in se obvežete, da boste zagotovili prevoz na zapisani relaciji in na zapisan datum (DATUM NAKLADA), v kolikor boste izbrani za prevoz..
        /// </summary>
        internal static string res_24 {
            get {
                return ResourceManager.GetString("res_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napačna zahteva.
        /// </summary>
        internal static string res_25 {
            get {
                return ResourceManager.GetString("res_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poslana zahteva ne ustreza!.
        /// </summary>
        internal static string res_26 {
            get {
                return ResourceManager.GetString("res_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poslana zahteva ne ustreza predvideni!.
        /// </summary>
        internal static string res_27 {
            get {
                return ResourceManager.GetString("res_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijava potekla!.
        /// </summary>
        internal static string res_28 {
            get {
                return ResourceManager.GetString("res_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žal je prijava za izbrano relacijo potekla..
        /// </summary>
        internal static string res_29 {
            get {
                return ResourceManager.GetString("res_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaša cena je bila uspešno posredovana.
        /// </summary>
        internal static string res_30 {
            get {
                return ResourceManager.GetString("res_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hvala za vašo prijavo!.
        /// </summary>
        internal static string res_31 {
            get {
                return ResourceManager.GetString("res_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaša cena je bila uspešno shranjena. O prevozu Vas bomo obvestili najmanj 3 dni pred datumom naklada..
        /// </summary>
        internal static string res_32 {
            get {
                return ResourceManager.GetString("res_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za kakršnakoli dodatna vprašanja smo vam na voljo na spodaj navedenih kontaktnih podatkih..
        /// </summary>
        internal static string res_33 {
            get {
                return ResourceManager.GetString("res_33", resourceCulture);
            }
        }
    }
}
